var observableStatic = Rx.Observable,
    observableWamp = Rx.WAMP = {},
    observableEmpty = observableStatic.empty,
    observableCreate = observableStatic.create,
    observablePromise = observableStatic.fromPromise,
    observerStatic = Rx.Observer,
    observerCreate = observerStatic.create,
    Subject = Rx.Subject,
    Disposable = Rx.Disposable,
    CompositeDisposable = Rx.CompositeDisposable,
    SerialDisposable = Rx.SerialDisposable,
    autobahn = autobahn || ab,
    sessionProto = autobahn.Session.prototype,
    isObservable = function(obs) { return obs && typeof obs.subscribe === 'function';},
    isPromise = Rx.helpers.isPromise,
    noop = Rx.helpers.noop;