var observableStatic = Rx.Observable,
    observableEmpty = observableStatic.empty,
    observableCreate = observableStatic.create,
    observablePromise = observableStatic.fromPromise,
    observerStatic = Rx.Observer,
    Subject = Rx.Subject,
    Disposable = Rx.Disposable,
    CompositeDisposable = Rx.CompositeDisposable,
    SerialDisposable = Rx.SerialDisposable,
    autobahn = autobahn || ab,
    sessionProto = autobahn.Session.prototype,
    isObservable = function(obs) { return obs && typeof obs.subscribe === 'function';};
